# Generated by Django 5.2.12 on 2026-03-24 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('check_in', models.TimeField()),
                ('check_out', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date', 'user_id'),
                'indexes': [models.Index(fields=['date'], name='entries_att_date_ace4da_idx'), models.Index(fields=['user', 'date'], name='entries_att_user_id_fa15b0_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='unique_user_date_attendance')],
            },
        ),
    ]
